### ISSUE TITLE
Dependency tkinter is missing

### ISSUE THREAD

**Issue by fhemberger** [hiway/mastodon-filter#1]
Followed the installation instructions on macOS, but got the following error:

```
Traceback (most recent call last):
  File "/Users/frederic/.local/bin/mastodon-filter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/frederic/.local/pipx/venvs/mastodon-filter/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/frederic/.local/pipx/venvs/mastodon-filter/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/frederic/.local/pipx/venvs/mastodon-filter/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/frederic/.local/pipx/venvs/mastodon-filter/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/frederic/.local/pipx/venvs/mastodon-filter/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/frederic/.local/pipx/venvs/mastodon-filter/lib/python3.11/site-packages/mastodon_filter/cli.py", line 28, in main_gui
    from mastodon_filter.gui import run_gui  # pylint: disable=import-outside-toplevel
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/frederic/.local/pipx/venvs/mastodon-filter/lib/python3.11/site-packages/mastodon_filter/gui/__init__.py", line 5, in <module>
    import tkinter as tk
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

Running `brew install python-tk` added the missing library. It should be either mentioned in the README as required step or added to the dependencies if possible.

**Comment by hiway** [comment]
Thank you.

The dependency is satisfied by the package manager for macOS; it will need to be installed AFAIK.

Updated the Readme with a requirements section.
